name: Update GitHub Readme Stats

on:
  schedule:
    - cron: "0 * * * *"
  push:
    branches: ["main"]

jobs:
  github-readme-stats:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v3

      - name: Run fetch script
        run: ./scripts/fetch.sh

      - name: Commit updated assets
        uses: EndBug/add-and-commit@v9
        with:
          add: ./assets/*.svg
          message: "chore: updated github readme stats"
          default_author: github_actions
